services:
  database:
    image: postgres
    hostname: database
    container_name: development-database
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - database-network
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  database-admin-tool:
    image: dpage/pgadmin4
    hostname: database-admin-tool
    container_name: development-database-admin-tool
    depends_on:
      - database
    ports:
      - '${ADMIN_TOOL_PORT}:80'
    networks:
      - database-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_TOOL_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_TOOL_PASSWORD}

networks:
  database-network:
    driver: bridge
